name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "ROBOTNAME=${{ secrets.ROBOTNAME }}" >> $GITHUB_ENV
        echo "DATABASE_EXCEL_PATH=SCADA TestData.xlsx" >> $GITHUB_ENV

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "."
        target: "~/app"

    - name: Run Deployment Script
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y python3 python3-pip python3-virtualenv unzip
          cd ~/app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          export GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
          export OPENAI_API_KEY=${OPENAI_API_KEY}
          export ROBOTNAME=${ROBOTNAME}
          export DATABASE_EXCEL_PATH=${DATABASE_EXCEL_PATH}
          nohup python3 app.py &
