name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "."
        target: "~/app"

    - name: Configure Environment Variables on EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          echo "export GOOGLE_CREDENTIALS='${{ secrets.GOOGLE_CREDENTIALS }}'" >> ~/.bashrc
          echo "export OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}'" >> ~/.bashrc
          echo "export ROBOTNAME='${{ secrets.ROBOTNAME }}'" >> ~/.bashrc
          echo "export DATABASE_EXCEL_PATH='SCADA TestData.xlsx'" >> ~/.bashrc
          source ~/.bashrc

    - name: Install Dependencies and Start App
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y python3 python3-pip python3-virtualenv unzip
          cd ~/app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python3 app.py &